name: atp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black=24.8.0
  - flake8
  - loguru
  - ipykernel
  - pytest
  - pytest-cov
  - pytest-dependency
  - seaborn
  - numpy
  - scipy
  - pytorch
  - pip
  - pip:
    - tensorflow
    - jax
    - jaxlib
